name: SVG to PNG and Upload to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger
  schedule:          # Automatic run every hour
    - cron: '0 * * * *'  # Runs at minute 0 every hour (UTC)

jobs:
  svg_to_png_upload:
    runs-on: ubuntu-latest

    env:
      BATCH_SIZE: 100          # Process 100 SVGs per run
      BATCH_START: 0           # You can increment this manually if needed
      GOOGLE_APPLICATION_CREDENTIALS: service_account.json

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests cairosvg google-auth google-api-python-client beautifulsoup4 selenium webdriver-manager

    - name: Restore service account key from base64
      run: echo "${{ secrets.SERVICE_ACCOUNT_BASE64 }}" | base64 -d > service_account.json

    - name: Run SVG to PNG upload script
      run: python main.py
