name: Download Pinterest Images to Google Drive

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight (UTC)
  workflow_dispatch:  # Allows manual trigger from GitHub interface

jobs:
  download_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pinterest scraper and upload to Google Drive
        env:
          SERVICE_ACCOUNT_BASE64: ${{ secrets.SERVICE_ACCOUNT_BASE64 }}
        run: |
          python main.py
