name: Run Python Script

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache duplicate tracking file
      uses: actions/cache@v3
      with:
        path: downloaded_urls.txt
        key: downloaded-urls-cache
        restore-keys: |
          downloaded-urls-cache

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set SERVICE_ACCOUNT_BASE64
      run: echo "SERVICE_ACCOUNT_BASE64=${{ secrets.SERVICE_ACCOUNT_BASE64 }}" >> $GITHUB_ENV

    - name: Run Python script
      run: |
        python main.py
